vim.cmd [[
  highlight clear
  if exists("syntax_on")
    syntax reset
  endif
]]

local theme = {
  bg = "#15181e",
  bg_alt = "#1b1f27",
  bg_light = "#2d3953",
  fg = "#d6e2ff",
  fg_dark = "#43547a",
  fg_darker = "#2d3953",
  accent_blue = "#83abfc",
  accent_cyan = "#83fcd4",
  accent_green = "#abfc83",
  accent_yellow = "#fcd483",
  accent_purple = "#d483fc",
  accent_pink = "#fc83ab",
  accent_orange = "#fcdc9c",
  diff_add = "#abfc83",
  diff_delete = "#fc83ab",
  diff_change = "#83abfc",
  border_add = "#abfc83",
  border_delete = "#fc83ab",
}

local highlights = {
  Normal = { fg = theme.fg, bg = theme.bg },
  NormalFloat = { fg = theme.fg, bg = theme.bg_alt },
  FloatBorder = { fg = theme.accent_blue, bg = theme.bg_alt },
  FloatTitle = { fg = theme.accent_blue, bg = theme.bg_alt, bold = true },
  LineNr = { fg = theme.fg_dark, bg = theme.bg },
  CursorLineNr = { fg = theme.accent_blue, bg = theme.bg, bold = true },
  CursorLine = { bg = theme.bg_light },
  CursorColumn = { bg = theme.bg_light },
  ColorColumn = { bg = theme.bg_light },
  Whitespace = { fg = theme.fg_dark },
  Pmenu = { fg = theme.fg, bg = theme.bg_alt },
  PmenuSel = { fg = theme.bg, bg = theme.accent_blue, bold = true },
  PmenuSbar = { bg = theme.bg_light },
  PmenuThumb = { bg = theme.accent_blue },
  WinSeparator = { fg = theme.bg_light },
  SignColumn = { bg = theme.bg },
  FoldColumn = { fg = theme.accent_blue, bg = theme.bg },
  Folded = { fg = theme.accent_blue, bg = theme.bg_light },
  MatchParen = { bg = theme.fg_dark, fg = theme.accent_blue, bold = true },
  DiagnosticError = { fg = theme.accent_pink },
  DiagnosticWarn = { fg = theme.accent_yellow },
  DiagnosticInfo = { fg = theme.accent_blue },
  DiagnosticHint = { fg = theme.accent_cyan },
  DiagnosticOk = { fg = theme.accent_green },
  DiagnosticSignError = { fg = theme.accent_pink },
  DiagnosticSignWarn = { fg = theme.accent_yellow },
  DiagnosticSignInfo = { fg = theme.accent_blue },
  DiagnosticSignHint = { fg = theme.accent_cyan },
  DiagnosticSignOk = { fg = theme.accent_green },
  DiagnosticVirtualTextError = { fg = theme.accent_pink },
  DiagnosticVirtualTextWarn = { fg = theme.accent_yellow },
  DiagnosticVirtualTextInfo = { fg = theme.accent_blue },
  DiagnosticVirtualTextHint = { fg = theme.accent_cyan },
  DiagnosticVirtualTextOk = { fg = theme.accent_green },
  DiagnosticUnderlineError = { undercurl = true, sp = theme.accent_pink },
  DiagnosticUnderlineWarn = { undercurl = true, sp = theme.accent_yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = theme.accent_blue },
  DiagnosticUnderlineHint = { undercurl = true, sp = theme.accent_cyan },
  DiagnosticUnderlineOk = { undercurl = true, sp = theme.accent_green },
  Error = { fg = theme.accent_pink },
  Warning = { fg = theme.accent_yellow },
  ErrorMsg = { fg = theme.accent_pink, bg = theme.bg },
  WarningMsg = { fg = theme.accent_yellow, bg = theme.bg },
  InfoMsg = { fg = theme.accent_blue, bg = theme.bg },
  HintMsg = { fg = theme.accent_cyan, bg = theme.bg },
  ModeMsg = { fg = theme.fg, bold = true },
  Comment = { fg = theme.fg_dark, bold = true },
  Todo = { fg = theme.accent_yellow, bg = theme.bg_light, bold = true },
  Conceal = { fg = theme.fg_dark },
  NonText = { fg = theme.fg_dark },
  SpecialKey = { fg = theme.fg_dark },
  String = { fg = theme.accent_green },
  Character = { fg = theme.accent_green },
  Number = { fg = theme.accent_yellow },
  Float = { fg = theme.accent_yellow },
  Boolean = { fg = theme.accent_purple },
  Identifier = { fg = theme.fg },
  Function = { fg = theme.accent_purple, italic = true },
  Operator = { fg = theme.accent_cyan },
  Keyword = { fg = theme.accent_purple },
  Statement = { fg = theme.accent_purple },
  Conditional = { fg = theme.accent_purple },
  Repeat = { fg = theme.accent_purple },
  Label = { fg = theme.accent_purple },
  Exception = { fg = theme.accent_purple },
  Type = { fg = theme.accent_blue },
  StorageClass = { fg = theme.accent_blue },
  Structure = { fg = theme.accent_blue },
  Typedef = { fg = theme.accent_blue },
  PreProc = { fg = theme.accent_blue },
  Include = { fg = theme.accent_blue },
  Define = { fg = theme.accent_blue },
  Macro = { fg = theme.accent_blue },
  PreCondit = { fg = theme.accent_blue },
  Special = { fg = theme.accent_cyan },
  SpecialChar = { fg = theme.accent_pink },
  SpecialComment = { fg = theme.accent_cyan, bold = true },
  Tag = { fg = theme.accent_pink },
  Delimiter = { fg = theme.fg },
  Underlined = { fg = theme.accent_blue, underline = true },
  Ignore = { fg = theme.fg_dark },
  Search = { fg = theme.bg, bg = theme.accent_yellow },
  IncSearch = { fg = theme.bg, bg = theme.accent_orange, bold = true },
  Substitute = { fg = theme.bg, bg = theme.accent_green },
  VisualNOS = { bg = theme.bg_light },
  Visual = { bg = theme.bg_light },
  QuickFixLine = { bg = theme.bg_light, bold = true },
  TabLine = { fg = theme.fg_dark, bg = theme.bg_alt },
  TabLineSel = { fg = theme.accent_blue, bg = theme.bg, bold = true },
  TabLineFill = { bg = theme.bg },
  StatusLine = { fg = theme.fg, bg = theme.bg_light },
  StatusLineNC = { fg = theme.fg_dark, bg = theme.bg_alt },
  StatusLineTermNC = { fg = theme.fg_dark, bg = theme.bg_alt },
  StatusLineTerm = { fg = theme.fg, bg = theme.bg_light },
  VertSplit = { fg = theme.bg_light },
  DiffAdd = { bg = theme.diff_add },
  DiffChange = { bg = theme.diff_change },
  DiffDelete = { bg = theme.diff_delete },
  DiffText = { bg = theme.diff_change, bold = true },
  DiffAdded = { fg = theme.accent_green },
  DiffRemoved = { fg = theme.accent_pink },
  DiffFile = { fg = theme.accent_blue, bold = true },
  DiffIndexLine = { fg = theme.fg_dark },
  PmenuKind = { fg = theme.accent_blue, bg = theme.bg_alt },
  PmenuKindSel = { fg = theme.bg, bg = theme.accent_blue },
  PmenuExtra = { fg = theme.accent_cyan, bg = theme.bg_alt },
  PmenuExtraSel = { fg = theme.bg, bg = theme.accent_cyan },
  SpellBad = { undercurl = true, sp = theme.accent_pink },
  SpellCap = { undercurl = true, sp = theme.accent_yellow },
  SpellLocal = { undercurl = true, sp = theme.accent_cyan },
  SpellRare = { undercurl = true, sp = theme.accent_purple },
  CursorIM = { fg = theme.bg, bg = theme.accent_blue },
  ToolbarLine = { fg = theme.fg, bg = theme.bg_light },
  ToolbarButton = { fg = theme.fg, bg = theme.bg_light, bold = true },
  TreesitterContext = { bg = theme.bg_light },
  TreesitterContextLineNumber = { fg = theme.accent_blue, bg = theme.bg_light },
  LspReferenceText = { bg = theme.bg_light },
  LspReferenceRead = { bg = theme.bg_light },
  LspReferenceWrite = { bg = theme.bg_light },
  LspSignatureActiveParameter = { fg = theme.accent_yellow, bold = true },
  WildMenu = { fg = theme.bg, bg = theme.accent_blue },
  IncCommandBuffer = { bg = theme.bg_light },
  IncCommandCursorLine = { bg = theme.bg_light },
}

for hl_group, hl_spec in pairs(highlights) do
  vim.api.nvim_set_hl(0, hl_group, hl_spec)
end

vim.g.colors_name = "lapis"
